version: '3.8'
services:
  mariadb:
    image: mariadb:11
    container_name: mariadb_db_name
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: db_webflux
      MARIADB_USER: root
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - volume_mariadb_db_name:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  volume_mariadb_db_name:
    external: false
